#version: '3.8'

services:
  #1. Base de Datos
  db:
    image: postgres:15
    container_name: db_callcenter
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: callcenter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #2. Servidor de Mensajes (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"   # Puerto de datos
      - "15672:15672" # Panel de control web , podemos acceder a http://localhost:15672 con usuario "guest" y contraseña "guest"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  #3. Nuestra Aplicación FastAPI, podemos acceder a http://localhost:8000/docs#/default/recibir_audio_subir_audio_post para probar la API
  api:
    build: .
    container_name: reception_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/callcenter_db
    depends_on:
      - db
      - rabbitmq
  #4. Microservicio: IA (Worker)
  ia_worker:
    build: ./2_transcription_worker
    container_name: ia_worker_whisper
    depends_on:
      - rabbitmq
      - db
    volumes:
      - ./audios:/app/audios  # Compartimos la carpeta de audios entre servicios
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/callcenter_db
      - RABBITMQ_HOST=rabbitmq

volumes:
  postgres_data:
